-- Executes only against the verified disposable runner target.
DO $$
DECLARE o bigint; g bigint; p bigint; actor uuid; leader uuid; member uuid;
 c uuid:=gen_random_uuid(); r jsonb; saved jsonb; dto jsonb; before_places bigint;
 denied boolean; v bigint; receipts bigint;
BEGIN
 PERFORM create_user_for_test('canonical_group_editor','canonical_group_editor@test.local');
 PERFORM create_user_for_test('canonical_group_leader','canonical_group_leader@test.local');
 PERFORM create_user_for_test('canonical_group_member','canonical_group_member@test.local');
 actor:=get_user_id('canonical_group_editor'); leader:=get_user_id('canonical_group_leader'); member:=get_user_id('canonical_group_member');
 INSERT INTO public.occasions(organization,unit,title,link,start_time,end_time,is_open)
 SELECT organization,id,'Canonical groups',gen_random_uuid()::text,now(),now()+interval '1 day',true FROM public.units LIMIT 1 RETURNING id INTO o;
 INSERT INTO public.occasion_users(occasion,"user",is_editor,is_editor_view,is_approved) VALUES(o,actor,true,true,true),(o,leader,false,false,true),(o,member,false,false,true);
 PERFORM set_config('request.jwt.claim.sub',actor::text,true);
 dto:=jsonb_build_object('title','Team','description','First','participants',jsonb_build_array(jsonb_build_object('user_id',leader,'is_admin',true),jsonb_build_object('user_id',member)), 'privatePlace',jsonb_build_object('title','Private','coordinates',jsonb_build_object('latLng',jsonb_build_object('lat',50,'lng',14))));
 r:=public.save_user_group_client_sync_v1(o,c,NULL,dto);
 PERFORM assert_eq(r->>'status','applied','create group and private place');
 saved:=r; g:=(r#>>'{data,group,id}')::bigint; p:=(r#>>'{data,group,place}')::bigint;
 PERFORM assert_true(g IS NOT NULL AND p IS NOT NULL,'authoritative IDs');
 PERFORM assert_eq((r#>>'{data,group,placeData,aggregate_version}')::int,1,'place version in save result');
 PERFORM assert_eq(public.save_user_group_client_sync_v1(o,c,NULL,dto),saved,'exact replay');
 dto:=dto||jsonb_build_object('id',g,'privatePlace',(dto->'privatePlace')||jsonb_build_object('id',p));
 r:=public.save_user_group_client_sync_v1(o,gen_random_uuid(),1,dto);
 PERFORM assert_eq(r->>'status','unchanged','normalized missing admin false is no-op');
 r:=public.move_place_client_sync_v1(o,p,gen_random_uuid(),1,51,15);
 PERFORM assert_eq(r->>'status','applied','canonical private move');
 r:=public.save_user_group_client_sync_v1(o,gen_random_uuid(),1,dto);
 PERFORM assert_eq(r->>'status','conflict','move advances group clock');
 PERFORM assert_eq((r#>>'{data,version}')::int,2,'conflict reports actual group clock');
 denied:=false;
 BEGIN
 PERFORM public.save_place_client_sync_v1(o,gen_random_uuid(),2,jsonb_build_object('id',p,'title','Bypass','type','public','isHidden',false,'coordinates',jsonb_build_object('latLng',jsonb_build_object('lat',51,'lng',15))));
 EXCEPTION WHEN invalid_parameter_value THEN denied:=true; END;
 PERFORM assert_true(denied,'generic map save cannot convert private group place');
 PERFORM set_config('request.jwt.claim.sub',leader::text,true);
 r:=public.get_user_group_editor_bundle_v1(o,g);
 PERFORM assert_eq((r->>'is_admin')::boolean,true,'leader narrow read carries actor permission');
 denied:=false;
 BEGIN PERFORM public.get_user_groups_editor_bundle_v1(o,NULL); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 PERFORM assert_true(denied,'leader cannot read admin list');
 dto:=jsonb_set(dto,'{privatePlace,coordinates}',jsonb_build_object('latLng',jsonb_build_object('lat',51,'lng',15)))||jsonb_build_object('description','Leader edit');
 c:=gen_random_uuid(); r:=public.save_user_group_client_sync_v1(o,c,2,dto);
 PERFORM assert_eq(r->>'status','applied','leader saves existing description');
 denied:=false;
 BEGIN PERFORM public.delete_user_group_client_sync_v1(o,g,gen_random_uuid(),3); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 PERFORM assert_true(denied,'leader cannot delete');
 UPDATE public.user_groups SET is_admin=false WHERE "group"=g AND "user"=leader;
 denied:=false;
 BEGIN PERFORM public.save_user_group_client_sync_v1(o,c,2,dto); EXCEPTION WHEN insufficient_privilege THEN denied:=true; END;
 PERFORM assert_true(denied,'removed leader cannot replay private response');
 PERFORM set_config('request.jwt.claim.sub',actor::text,true);
 denied:=false;
 BEGIN PERFORM public.save_user_group_client_sync_v1(o,gen_random_uuid(),3,jsonb_set(dto,'{participants}',jsonb_build_array(jsonb_build_object('user_id',member,'extra',1)))); EXCEPTION WHEN invalid_parameter_value THEN denied:=true; END;
 PERFORM assert_true(denied,'unknown participant fields reject');
 SELECT count(*) INTO before_places FROM public.places;
 ALTER TABLE public.user_group_info ADD CONSTRAINT canonical_group_failure CHECK(title<>'Injected group failure');
 c:=gen_random_uuid(); denied:=false;
 BEGIN PERFORM public.save_user_group_client_sync_v1(o,c,NULL,jsonb_build_object('title','Injected group failure','participants','[]'::jsonb,'privatePlace',jsonb_build_object('title','Rollback','coordinates',jsonb_build_object('latLng',jsonb_build_object('lat',50,'lng',14))))); EXCEPTION WHEN check_violation THEN denied:=true; END;
 PERFORM assert_true(denied,'injected group persistence failure');
 PERFORM assert_eq((SELECT count(*) FROM public.places),before_places,'private place rolls back');
 PERFORM assert_eq((SELECT count(*) FROM public.client_mutation_receipts WHERE command_id=c),0::bigint,'receipt rolls back');
 ALTER TABLE public.user_group_info DROP CONSTRAINT canonical_group_failure;
 r:=public.replace_group_assignments_client_sync_v1(o,gen_random_uuid(),jsonb_build_array(jsonb_build_object('user_id',member,'group_title','Team')));
 PERFORM assert_eq(r->>'status','unchanged','same membership import is no-op');
 PERFORM assert_true(NOT has_function_privilege('authenticated','public.lock_group_occasion_internal_v1(bigint)','EXECUTE'),'lock helper ungranted');
 PERFORM assert_true(NOT has_function_privilege('anon','public.get_user_group_editor_bundle_v1(bigint,bigint)','EXECUTE'),'narrow read not anonymous');
END $$;

DO $$
DECLARE o bigint; foreign_o bigint; actor uuid; foreign_user uuid; group_id bigint; private_id bigint; shared_id bigint; a uuid:=gen_random_uuid(); x uuid:=gen_random_uuid(); result jsonb; dto jsonb; denied boolean;
BEGIN
 PERFORM create_user_for_test('canonical_place_lifecycle','canonical_place_lifecycle@test.local');actor:=get_user_id('canonical_place_lifecycle');
 PERFORM create_user_for_test('canonical_foreign_member','canonical_foreign_member@test.local');foreign_user:=get_user_id('canonical_foreign_member');
 INSERT INTO public.occasions(organization,unit,title,link,start_time,end_time,is_open) SELECT organization,id,'Place lifecycle',gen_random_uuid()::text,now(),now()+interval '1 day',true FROM public.units LIMIT 1 RETURNING id INTO o;
 INSERT INTO public.occasions(organization,unit,title,link,start_time,end_time,is_open) SELECT organization,id,'Foreign group scope',gen_random_uuid()::text,now(),now()+interval '1 day',true FROM public.units LIMIT 1 RETURNING id INTO foreign_o;
 INSERT INTO public.occasion_users(occasion,"user",is_editor,is_editor_view,is_approved) VALUES(o,actor,true,true,true),(foreign_o,foreign_user,false,false,true);
 PERFORM set_config('request.jwt.claim.sub',actor::text,true);
 dto:=jsonb_build_object('title','Lifecycle','participants',jsonb_build_array(jsonb_build_object('user_id',actor)), 'privatePlace',jsonb_build_object('title','Owned','coordinates',jsonb_build_object('latLng',jsonb_build_object('lat',50,'lng',14))));
 result:=public.save_user_group_client_sync_v1(o,gen_random_uuid(),NULL,dto);group_id:=(result#>>'{data,group,id}')::bigint;private_id:=(result#>>'{data,group,place}')::bigint;
 INSERT INTO public.activities(id,title,occasion,is_hidden,"order") VALUES(a,'External reference',o,false,0);
 INSERT INTO public.activity_assignments(id,activity_id,"user",start_time,end_time) VALUES(x,a,actor,now(),now()+interval '1 hour');
 INSERT INTO public.activity_assignment_places(assignment_id,place_id) VALUES(x,private_id);
 denied:=false;BEGIN PERFORM public.delete_user_group_client_sync_v1(o,group_id,gen_random_uuid(),1);EXCEPTION WHEN invalid_parameter_value THEN denied:=true;END;
 PERFORM assert_true(denied,'group deletion rejects external assignment cascade');
 PERFORM assert_true(EXISTS(SELECT 1 FROM public.activity_assignment_places WHERE assignment_id=x AND place_id=private_id),'rejected group deletion preserves external link');
 denied:=false;BEGIN PERFORM public.save_user_group_client_sync_v1(o,gen_random_uuid(),1,(dto-'privatePlace')||jsonb_build_object('id',group_id));EXCEPTION WHEN invalid_parameter_value THEN denied:=true;END;
 PERFORM assert_true(denied,'detach cannot cascade an external assignment');
 DELETE FROM public.activity_assignment_places WHERE assignment_id=x;
 INSERT INTO public.places(title,occasion,is_hidden,type) VALUES('Shared',o,false,'point') RETURNING id INTO shared_id;
 dto:=(dto-'privatePlace')||jsonb_build_object('id',group_id,'placeId',shared_id);
 result:=public.save_user_group_client_sync_v1(o,gen_random_uuid(),1,dto);
 PERFORM assert_eq(result->>'status','applied','private to shared place transition');
 PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.places WHERE id=private_id),'detached unreferenced owned place deleted');
 result:=public.save_user_group_client_sync_v1(o,gen_random_uuid(),2,dto||jsonb_build_object('placeId',NULL));
 PERFORM assert_eq(result->>'status','applied','shared to no place transition');
 PERFORM assert_true(EXISTS(SELECT 1 FROM public.places WHERE id=shared_id),'shared place is preserved');
 INSERT INTO public.activity_assignment_places(assignment_id,place_id) VALUES(x,shared_id);
 result:=public.delete_place_client_sync_v1(o,shared_id,gen_random_uuid(),0);
 PERFORM assert_eq(result->>'status','rejected','generic shared place delete cannot cascade into activity graph');
 PERFORM assert_true(EXISTS(SELECT 1 FROM public.activity_assignment_places WHERE assignment_id=x AND place_id=shared_id),'generic delete preserves activity link');
 denied:=false;BEGIN PERFORM public.save_user_group_client_sync_v1(o,gen_random_uuid(),3,jsonb_set(dto,'{participants}',jsonb_build_array(jsonb_build_object('user_id',foreign_user))));EXCEPTION WHEN invalid_parameter_value THEN denied:=true;END;
 PERFORM assert_true(denied,'foreign participant rejected');
 denied:=false;BEGIN PERFORM public.save_user_group_client_sync_v1(o,gen_random_uuid(),3,jsonb_set(dto,'{participants}',jsonb_build_array(jsonb_build_object('user_id',actor),jsonb_build_object('user_id',actor))));EXCEPTION WHEN invalid_parameter_value THEN denied:=true;END;
 PERFORM assert_true(denied,'duplicate participant rejected');
 result:=public.save_user_group_client_sync_v1(o,gen_random_uuid(),3,(dto-'placeId')||jsonb_build_object('participants','[]'::jsonb));
 PERFORM assert_eq(result->>'status','applied','empty complete membership set');
 PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.user_groups WHERE "group"=group_id),'empty membership persisted atomically');
END $$;
