-- Shared terms only. The existing planned_changes queue remains the executor input.
CREATE TABLE IF NOT EXISTS eshop.product_price_waves (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occasion bigint NOT NULL REFERENCES public.occasions(id) ON DELETE CASCADE,
  change_time timestamptz NOT NULL,
  revision bigint NOT NULL DEFAULT 1,
  UNIQUE(occasion,change_time)
);
ALTER TABLE eshop.product_price_waves ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE eshop.product_price_waves FROM PUBLIC,anon,authenticated;
REVOKE ALL ON SEQUENCE eshop.product_price_waves_id_seq FROM PUBLIC,anon,authenticated;
ALTER TABLE eshop.planned_changes ADD COLUMN IF NOT EXISTS wave_id bigint
  REFERENCES eshop.product_price_waves(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX IF NOT EXISTS planned_product_wave_target_unique
  ON eshop.planned_changes(wave_id,subject_id,change_type)
  WHERE wave_id IS NOT NULL AND NOT applied;

CREATE OR REPLACE FUNCTION public.check_product_wave_editor(p_occasion bigint)
RETURNS void LANGUAGE plpgsql SET search_path=public,extensions AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT EXISTS(SELECT 1 FROM public.occasions o
    JOIN public.user_info ui ON ui.organization=o.organization
    WHERE o.id=p_occasion AND ui.id=auth.uid()) THEN
    RAISE insufficient_privilege USING MESSAGE='ORDER_EDITOR_REQUIRED';
  END IF;
  PERFORM public.check_is_editor_order_on_occasion(p_occasion);
END; $$;
REVOKE ALL ON FUNCTION public.check_product_wave_editor(bigint) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.create_product_price_wave(p_occasion_link text,p_change_time timestamptz)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,extensions AS $$
DECLARE v_occasion bigint; v_wave eshop.product_price_waves%ROWTYPE;
BEGIN
  SELECT o.id INTO STRICT v_occasion FROM public.occasions o JOIN public.user_info ui
    ON ui.organization=o.organization WHERE o.link=p_occasion_link AND ui.id=auth.uid();
  PERFORM public.check_product_wave_editor(v_occasion);
  IF p_change_time IS NULL OR NOT isfinite(p_change_time) OR p_change_time<=clock_timestamp() THEN
    RAISE invalid_parameter_value USING MESSAGE='FUTURE_TIME_REQUIRED'; END IF;
  INSERT INTO eshop.product_price_waves(occasion,change_time) VALUES(v_occasion,p_change_time)
    ON CONFLICT(occasion,change_time) DO NOTHING;
  SELECT * INTO STRICT v_wave FROM eshop.product_price_waves
    WHERE occasion=v_occasion AND change_time=p_change_time FOR UPDATE;
  -- Adopt existing unambiguous targets at this shared term without repricing.
  PERFORM 1 FROM eshop.products p WHERE p.occasion=v_occasion AND EXISTS(
    SELECT 1 FROM eshop.planned_changes pc WHERE pc.subject_id=p.id AND pc.occasion=v_occasion
      AND pc.change_time=p_change_time AND pc.change_type IN('products.price','products.is_hidden') AND NOT pc.applied)
    ORDER BY p.id FOR UPDATE;
  UPDATE eshop.planned_changes pc SET wave_id=v_wave.id
    WHERE pc.occasion=v_occasion AND pc.change_time=p_change_time AND NOT pc.applied AND pc.wave_id IS NULL
      AND pc.change_type IN('products.price','products.is_hidden') AND EXISTS(
        SELECT 1 FROM eshop.products p JOIN eshop.product_types pt ON pt.id=p.product_type
        WHERE p.id=pc.subject_id AND p.occasion=v_occasion AND pt.occasion=v_occasion)
      AND (SELECT count(*) FROM eshop.planned_changes other WHERE other.subject_id=pc.subject_id
        AND other.change_type=pc.change_type AND other.change_time=pc.change_time AND NOT other.applied)=1;
  IF p_change_time<=clock_timestamp() THEN RAISE invalid_parameter_value USING MESSAGE='FUTURE_TIME_REQUIRED'; END IF;
  RETURN to_jsonb(v_wave);
END; $$;
REVOKE ALL ON FUNCTION public.create_product_price_wave(text,timestamptz) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.create_product_price_wave(text,timestamptz) TO authenticated;

CREATE OR REPLACE FUNCTION public.save_product_wave_target(
  p_wave_id bigint,p_product_id bigint,p_expected_wave_revision bigint,p_price numeric,p_is_hidden boolean,
  p_expected_price_revision bigint DEFAULT NULL,p_expected_visibility_revision bigint DEFAULT NULL
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,extensions AS $$
DECLARE v_wave eshop.product_price_waves%ROWTYPE; v_product eshop.products%ROWTYPE;
  v_price eshop.planned_changes%ROWTYPE; v_visibility eshop.planned_changes%ROWTYPE;
BEGIN
  SELECT * INTO STRICT v_wave FROM eshop.product_price_waves WHERE id=p_wave_id FOR UPDATE;
  PERFORM public.check_product_wave_editor(v_wave.occasion);
  IF v_wave.revision IS DISTINCT FROM p_expected_wave_revision THEN RAISE serialization_failure USING MESSAGE='PRICE_CHANGE_CONFLICT'; END IF;
  IF v_wave.change_time<=clock_timestamp() THEN RAISE invalid_parameter_value USING MESSAGE='FUTURE_TIME_REQUIRED'; END IF;
  SELECT * INTO STRICT v_product FROM eshop.products WHERE id=p_product_id FOR UPDATE;
  IF v_product.occasion IS DISTINCT FROM v_wave.occasion OR NOT EXISTS(
    SELECT 1 FROM eshop.product_types WHERE id=v_product.product_type AND occasion=v_wave.occasion) THEN
    RAISE insufficient_privilege USING MESSAGE='PRODUCT_OCCASION_MISMATCH'; END IF;
  IF v_wave.change_time<=clock_timestamp() THEN RAISE invalid_parameter_value USING MESSAGE='FUTURE_TIME_REQUIRED'; END IF;
  -- Lock in the same subject/plan order as the executor and single-product editor.
  PERFORM 1 FROM eshop.planned_changes WHERE subject_id=p_product_id AND wave_id=p_wave_id
    AND NOT applied ORDER BY id FOR UPDATE;
  SELECT * INTO v_price FROM eshop.planned_changes WHERE subject_id=p_product_id
    AND wave_id=p_wave_id AND change_type='products.price' AND NOT applied;
  SELECT * INTO v_visibility FROM eshop.planned_changes WHERE subject_id=p_product_id
    AND wave_id=p_wave_id AND change_type='products.is_hidden' AND NOT applied;
  IF v_price.revision IS DISTINCT FROM p_expected_price_revision OR
    v_visibility.revision IS DISTINCT FROM p_expected_visibility_revision THEN
    RAISE serialization_failure USING MESSAGE='PRICE_CHANGE_CONFLICT'; END IF;
  IF EXISTS(SELECT 1 FROM eshop.planned_changes WHERE subject_id=p_product_id
    AND change_time=v_wave.change_time AND NOT applied AND wave_id IS DISTINCT FROM p_wave_id
    AND ((change_type='products.price' AND p_price IS NOT NULL) OR
         (change_type='products.is_hidden' AND p_is_hidden IS NOT NULL))) THEN
    RAISE serialization_failure USING MESSAGE='PRICE_CHANGE_CONFLICT'; END IF;
  IF p_price IS NOT NULL THEN
    PERFORM public.validate_product_price(p_price,v_product.data,v_product.currency_code);
    IF v_price.id IS NULL THEN
      INSERT INTO eshop.planned_changes(change_type,subject_id,new_value,change_time,occasion,wave_id)
        VALUES('products.price',p_product_id,p_price::text,v_wave.change_time,v_wave.occasion,p_wave_id);
    ELSE
      UPDATE eshop.planned_changes SET new_value=p_price::text,failed_at=NULL,failure_code=NULL,revision=revision+1 WHERE id=v_price.id;
    END IF;
  ELSIF v_price.id IS NOT NULL THEN DELETE FROM eshop.planned_changes WHERE id=v_price.id;
  END IF;
  IF p_is_hidden IS NOT NULL THEN
    IF v_visibility.id IS NULL THEN
      INSERT INTO eshop.planned_changes(change_type,subject_id,new_value,change_time,occasion,wave_id)
        VALUES('products.is_hidden',p_product_id,p_is_hidden::text,v_wave.change_time,v_wave.occasion,p_wave_id);
    ELSE
      UPDATE eshop.planned_changes SET new_value=p_is_hidden::text,failed_at=NULL,failure_code=NULL,revision=revision+1 WHERE id=v_visibility.id;
    END IF;
  ELSIF v_visibility.id IS NOT NULL THEN DELETE FROM eshop.planned_changes WHERE id=v_visibility.id;
  END IF;
END; $$;
REVOKE ALL ON FUNCTION public.save_product_wave_target(bigint,bigint,bigint,numeric,boolean,bigint,bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.save_product_wave_target(bigint,bigint,bigint,numeric,boolean,bigint,bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.move_product_price_wave(p_wave_id bigint,p_expected_revision bigint,p_change_time timestamptz)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,extensions AS $$
DECLARE v_wave eshop.product_price_waves%ROWTYPE;
BEGIN
  SELECT * INTO STRICT v_wave FROM eshop.product_price_waves WHERE id=p_wave_id FOR UPDATE;
  PERFORM public.check_product_wave_editor(v_wave.occasion);
  IF v_wave.revision IS DISTINCT FROM p_expected_revision THEN RAISE serialization_failure USING MESSAGE='PRICE_CHANGE_CONFLICT'; END IF;
  IF p_change_time IS NULL OR NOT isfinite(p_change_time) OR p_change_time<=clock_timestamp() THEN
    RAISE invalid_parameter_value USING MESSAGE='FUTURE_TIME_REQUIRED'; END IF;
  IF EXISTS(SELECT 1 FROM eshop.planned_changes WHERE wave_id=p_wave_id AND applied) THEN
    RAISE invalid_parameter_value USING MESSAGE='WAVE_ALREADY_APPLIED'; END IF;
  PERFORM 1 FROM eshop.products WHERE id IN(SELECT subject_id FROM eshop.planned_changes
    WHERE wave_id=p_wave_id AND NOT applied) ORDER BY id FOR UPDATE;
  PERFORM 1 FROM eshop.planned_changes WHERE wave_id=p_wave_id AND NOT applied ORDER BY subject_id,id FOR UPDATE;
  IF EXISTS(SELECT 1 FROM eshop.planned_changes target JOIN eshop.planned_changes other
    ON other.subject_id=target.subject_id AND other.change_type=target.change_type
    WHERE target.wave_id=p_wave_id AND NOT target.applied AND NOT other.applied
      AND other.wave_id IS DISTINCT FROM p_wave_id AND other.change_time=p_change_time) THEN
    RAISE serialization_failure USING MESSAGE='PRICE_CHANGE_CONFLICT'; END IF;
  IF EXISTS(SELECT 1 FROM eshop.planned_changes WHERE wave_id=p_wave_id AND applied) THEN
    RAISE invalid_parameter_value USING MESSAGE='WAVE_ALREADY_APPLIED'; END IF;
  IF p_change_time<=clock_timestamp() THEN RAISE invalid_parameter_value USING MESSAGE='FUTURE_TIME_REQUIRED'; END IF;
  UPDATE eshop.product_price_waves SET change_time=p_change_time,revision=revision+1 WHERE id=p_wave_id RETURNING * INTO v_wave;
  UPDATE eshop.planned_changes SET change_time=p_change_time,revision=revision+1,failed_at=NULL,failure_code=NULL
    WHERE wave_id=p_wave_id AND NOT applied;
  RETURN to_jsonb(v_wave);
END; $$;
REVOKE ALL ON FUNCTION public.move_product_price_wave(bigint,bigint,timestamptz) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.move_product_price_wave(bigint,bigint,timestamptz) TO authenticated;

CREATE OR REPLACE FUNCTION public.cancel_product_price_wave(p_wave_id bigint,p_expected_revision bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,extensions AS $$
DECLARE v_wave eshop.product_price_waves%ROWTYPE;
BEGIN
  SELECT * INTO STRICT v_wave FROM eshop.product_price_waves WHERE id=p_wave_id FOR UPDATE;
  PERFORM public.check_product_wave_editor(v_wave.occasion);
  IF v_wave.revision IS DISTINCT FROM p_expected_revision THEN RAISE serialization_failure USING MESSAGE='PRICE_CHANGE_CONFLICT'; END IF;
  PERFORM 1 FROM eshop.products WHERE id IN(SELECT subject_id FROM eshop.planned_changes
    WHERE wave_id=p_wave_id AND NOT applied) ORDER BY id FOR UPDATE;
  DELETE FROM eshop.planned_changes WHERE wave_id=p_wave_id AND NOT applied;
  DELETE FROM eshop.product_price_waves WHERE id=p_wave_id;
END; $$;
REVOKE ALL ON FUNCTION public.cancel_product_price_wave(bigint,bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.cancel_product_price_wave(bigint,bigint) TO authenticated;
