BEGIN;
DO $$
DECLARE org bigint; unit_id bigint; occ bigint; msg jsonb; replay jsonb; row jsonb; started jsonb; att uuid; token uuid; context jsonb; v_order_id bigint; editor uuid; foreign_occ bigint; v_history int;
BEGIN
 INSERT INTO public.organizations(title) VALUES('Email contract fixture') RETURNING id INTO org;
 INSERT INTO public.units(title,organization) VALUES('Email unit',org) RETURNING id INTO unit_id;
 INSERT INTO public.occasions(title,organization,unit,link,start_time,end_time) VALUES('Email occasion',org,unit_id,'email-fixture-'||gen_random_uuid(),now(),now()+interval '1 day') RETURNING id INTO occ;
 context:=jsonb_build_object('organization',org,'occasion',occ,'unit',unit_id);
 msg:=public.enqueue_email('custom',context,'fixture@example.invalid','{}','contract-replay');
 replay:=public.enqueue_email('custom',context,'fixture@example.invalid','{}','contract-replay');
 PERFORM assert_eq(msg->>'message_id',replay->>'message_id','same intent replays');
 BEGIN PERFORM public.enqueue_email('custom',context,'fixture@example.invalid','{"changed":true}','contract-replay');RAISE EXCEPTION 'collision was allowed';
 EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'email_dedupe_conflict' THEN RAISE; END IF; END;
 PERFORM assert_true(NOT has_function_privilege('anon','public.enqueue_email(text,jsonb,text,jsonb,text,text,timestamptz,timestamptz,bigint,bigint,jsonb)','EXECUTE'),'anon cannot enqueue');
 PERFORM assert_true(NOT has_function_privilege('anon','public.generate_request_secret(integer)','EXECUTE'),'public cannot mint worker proof');
 PERFORM assert_true(NOT has_table_privilege('anon','public.request_secrets','SELECT'),'public cannot steal worker proof');
 PERFORM assert_true(NOT has_table_privilege('authenticated','public.email_messages','SELECT'),'queue bodies private');
 UPDATE public.email_messages SET workflow_state='cancelled' WHERE message_id<>(msg->>'message_id')::uuid;
 UPDATE public.email_capacity SET paused=false,quota_at=now(),max_rate=1,daily_quota=100,provider_sent_24h=0,shared_account=false,next_send_at=now(),worker_url=NULL;
 row:=public.claim_email();att:=(row->>'attempt_id')::uuid;token:=(row->>'lease_token')::uuid;
 PERFORM assert_eq(row->>'message_id',msg->>'message_id','claim expected intent');
 PERFORM public.prepare_email((msg->>'message_id')::uuid,token,'{"sealed":"snapshot"}');
 started:=public.begin_email_send(att,token);
 PERFORM assert_eq(started->>'disposition','send','provider begin owns permit');
 started:=public.begin_email_send(att,token);
 PERFORM assert_eq(started->>'disposition','replay','gateway replay cannot send');
 PERFORM public.finish_email_attempt(att,token,'unknown',NULL,'transport_ambiguous');
 PERFORM assert_eq(public.get_internal_email_state((msg->>'message_id')::uuid),'unknown','timeout stays unknown');
 PERFORM assert_true(public.claim_email() IS NULL,'unknown never auto-retries');
 -- Feedback arrives before API acceptance is saved and reconciles without replay.
 PERFORM public.record_email_event(jsonb_build_object('key','event-contract','provider_id','ses-fixture','attempt_id',att,'recipient','fixture@example.invalid','type','delivery','time',now()));
 PERFORM assert_eq(public.get_internal_email_state((msg->>'message_id')::uuid),'accepted','trusted feedback resolves unknown');
 PERFORM public.record_email_event(jsonb_build_object('key','event-contract','provider_id','ses-fixture','attempt_id',att,'recipient','fixture@example.invalid','type','delivery','time',now()));
 PERFORM assert_eq((SELECT count(*)::int FROM public.email_delivery_events WHERE event_key='event-contract'),1,'duplicate event is one record');
 PERFORM public.record_email_event(jsonb_build_object('key','event-bounce','provider_id','ses-fixture','attempt_id',att,'recipient','fixture@example.invalid','type','bounce','time',now(),'hard_bounce',true));
 PERFORM assert_eq((SELECT reason FROM public.email_suppressions WHERE recipient='fixture@example.invalid'),'hard_bounce','hard bounce suppresses future sends');
 PERFORM assert_eq((SELECT public.email_reporting_state(m) FROM public.email_messages m WHERE message_id=(msg->>'message_id')::uuid),'bounce','bounce beats accepted');
 -- Independent capacity scenario after the preceding outage observation.
 PERFORM assert_true((SELECT circuit_until>now() FROM public.email_capacity),'unknown provider result keeps an outage circuit');
 UPDATE public.email_capacity SET circuit_until=NULL,provider_outage_streak=0,probe_until=NULL;
 -- A capacity deferral changes no retry count and retains the immutable snapshot.
 msg:=public.enqueue_email('custom',context,'other@example.invalid','{}','capacity-contract');
 row:=public.claim_email();att:=(row->>'attempt_id')::uuid;token:=(row->>'lease_token')::uuid;
 PERFORM public.prepare_email((msg->>'message_id')::uuid,token,'{"sealed":"immutable"}');
 UPDATE public.email_capacity SET paused=true;
 started:=public.begin_email_send(att,token);
 PERFORM assert_eq(started->>'disposition','deferred','paused provider defers in same queue');
 PERFORM assert_eq((SELECT attempt_count FROM public.email_messages WHERE message_id=(msg->>'message_id')::uuid),0,'capacity is not a failed attempt');
 PERFORM assert_eq((SELECT prepared->>'sealed' FROM public.email_messages WHERE message_id=(msg->>'message_id')::uuid),'immutable','deferral keeps prepared snapshot');
 -- Tenant and order summaries: later success cannot hide failed tickets.
 INSERT INTO eshop.orders(order_symbol, occasion,state,data,price,currency_code) VALUES(public.generate_order_symbol(), occ,'paid','{"email":"order@example.invalid"}',100,'CZK') RETURNING id INTO v_order_id;
 msg:=public.enqueue_order_email('ORDER_TICKETS',jsonb_build_object('order_id',v_order_id),org,occ,unit_id);
 UPDATE public.email_messages SET workflow_state='accepted',accepted_at=now(),bounced_at=now() WHERE message_id=(msg->>'message_id')::uuid;
 PERFORM public.enqueue_order_email('TICKET_ORDER_UPDATE',jsonb_build_object('order_id',v_order_id),org,occ,unit_id);
 UPDATE public.email_messages SET workflow_state='accepted',accepted_at=now(),delivered_at=now() WHERE order_id=v_order_id AND message_kind='order_update';
 PERFORM create_user_for_test('email_editor','editor@example.invalid');editor:=get_user_id('email_editor');
 INSERT INTO public.occasion_users(occasion,"user",is_editor_order_view) VALUES(occ,editor,true);
 PERFORM set_config('request.jwt.claim.sub',editor::text,true);
 PERFORM assert_eq(public.get_order_email_summary(v_order_id)->>'state','bounce','later success does not hide bounced tickets');
 PERFORM assert_eq(public.get_order_email_summary(v_order_id)->>'attention_count','1','attention is per message');
 -- Order history excludes unrelated mail before limiting/pagination, preserving old callers.
 PERFORM assert_eq(jsonb_array_length(public.get_email_delivery_page(occ,p_orders_only=>true)),2,'only order messages in occasion');
 PERFORM assert_true(jsonb_array_length(public.get_email_delivery_page(occ))>2,'default page retains unrelated messages for old clients');
 row:=public.get_email_delivery_page(occ,p_limit=>1,p_orders_only=>true)->0;
 PERFORM assert_eq((row->>'order_id')::bigint,v_order_id,'first order-only page carries order identity');
 PERFORM assert_eq(jsonb_array_length(public.get_email_delivery_page(occ,p_before=>(row->>'id')::bigint,p_limit=>1,p_orders_only=>true)),1,'next order-only page does not disappear behind unrelated mail');
 UPDATE email_messages SET message_kind='legacy_unknown' WHERE order_id=v_order_id AND message_kind='order_update';
 PERFORM assert_eq(jsonb_array_length(public.get_email_delivery_page(occ,p_orders_only=>true)),2,'historical order mail remains visible');
 UPDATE email_messages SET message_kind='order_update' WHERE order_id=v_order_id AND message_kind='legacy_unknown';
 PERFORM assert_true(NOT has_function_privilege('anon','public.get_email_delivery_page(bigint,bigint,integer,bigint,text,text,bigint,uuid,timestamptz,boolean)','EXECUTE'),'order history remains private');
 SELECT count(*) INTO v_history FROM eshop.orders_history WHERE "order"=v_order_id;
 PERFORM public.apply_email_post_actions((msg->>'message_id')::uuid);
 PERFORM assert_eq((SELECT state FROM eshop.orders WHERE id=v_order_id),'sent','accepted current ticket projection updates paid order');
 PERFORM assert_eq((SELECT post_action_state FROM public.email_messages WHERE message_id=(msg->>'message_id')::uuid),'done','projection commits its receipt');
 PERFORM public.apply_email_post_actions((msg->>'message_id')::uuid);
 PERFORM assert_eq((SELECT count(*)::int FROM eshop.orders_history WHERE "order"=v_order_id),v_history+1,'post-action replay adds no duplicate history');
 INSERT INTO public.occasions(title,organization,unit,link,start_time,end_time) VALUES('Other scope',org,unit_id,gen_random_uuid()::text,now(),now()+interval '1 day') RETURNING id INTO foreign_occ;
 BEGIN PERFORM public.get_email_delivery_page(foreign_occ);RAISE EXCEPTION 'cross scope allowed';EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'email_read_denied' THEN RAISE;END IF;END;
 BEGIN PERFORM public.get_order_email_summaries(foreign_occ,ARRAY[v_order_id]);RAISE EXCEPTION 'forged order allowed';EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'email_read_denied' THEN RAISE;END IF;END;
 PERFORM public.enqueue_order_email('TICKET_ORDER_CONFIRMATION',jsonb_build_object('order_id',v_order_id,'command_id','00000000-0000-4000-8000-000000000001'),org,occ,unit_id);
 PERFORM assert_true(public.create_email_confirmation_receipt('00000000-0000-4000-8000-000000000001',v_order_id,repeat('c',64)),'receipt tied to committed confirmation');
 PERFORM assert_eq(public.get_email_confirmation_status(repeat('c',64)),'queued','receipt exposes coarse status');
 PERFORM assert_eq(public.get_email_confirmation_status(repeat('d',64)),'unavailable','random capability reveals nothing');
 UPDATE public.email_messages SET workflow_state='accepted',provider_message_id='receipt-provider' WHERE message_id=(SELECT message_id FROM public.email_confirmation_receipts WHERE token_hash=repeat('c',64));
 PERFORM public.record_email_event(jsonb_build_object('key','receipt-invalid','provider_id','receipt-provider','recipient','order@example.invalid','type','bounce','time',now(),'hard_bounce',true,'invalid_recipient',true));
 PERFORM assert_eq(public.get_email_confirmation_status(repeat('c',64)),'invalid_email','verified address failure is visible through the bounded capability');
 UPDATE public.email_confirmation_receipts SET reads=15;
 PERFORM assert_eq(public.get_email_confirmation_status(repeat('c',64)),'unavailable','receipt rate budget enforced');

 -- Lease recovery still runs while provider access is paused/unavailable.
 UPDATE public.email_messages SET workflow_state='cancelled' WHERE workflow_state IN ('pending','preparing','blocked','retry_wait');
 UPDATE public.email_capacity SET paused=false,next_send_at=now();
 msg:=public.enqueue_email('custom',context,'lease@example.invalid','{}','lease-recovery-contract');
 row:=public.claim_email();att:=(row->>'attempt_id')::uuid;token:=(row->>'lease_token')::uuid;
 PERFORM public.prepare_email((msg->>'message_id')::uuid,token,'{"sealed":"lease-fixture"}');
 PERFORM public.begin_email_send(att,token);
 UPDATE public.email_messages SET lease_until=now()-interval '1 second' WHERE message_id=(msg->>'message_id')::uuid;
 UPDATE public.email_capacity SET paused=true;
 PERFORM public.recover_email_delivery();
 PERFORM assert_eq(public.get_internal_email_state((msg->>'message_id')::uuid),'unknown','paused recovery does not report expired send as sending');
 PERFORM assert_true(public.claim_email() IS NULL,'ambiguous expired send remains quarantined');
 BEGIN PERFORM public.reconcile_unknown_email((msg->>'message_id')::uuid,'known_not_accepted','');RAISE EXCEPTION 'missing evidence allowed';EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'reconciliation_evidence_required' THEN RAISE;END IF;END;
 BEGIN PERFORM public.reconcile_unknown_email((msg->>'message_id')::uuid,'accepted','operator checked provider');RAISE EXCEPTION 'missing provider receipt allowed';EXCEPTION WHEN OTHERS THEN IF SQLERRM<>'provider_receipt_required' THEN RAISE;END IF;END;
 PERFORM public.reconcile_unknown_email((msg->>'message_id')::uuid,'known_not_accepted','provider investigation proves no acceptance');
 PERFORM assert_eq(public.get_internal_email_state((msg->>'message_id')::uuid),'pending','evidence-backed non-acceptance permits retry');
 PERFORM assert_true((SELECT post_action->'reconciliation'->>'evidence' IS NOT NULL FROM public.email_messages WHERE message_id=(msg->>'message_id')::uuid),'operator decision is audited');
 PERFORM assert_true(NOT has_function_privilege('anon','public.get_email_delivery_detail(uuid)','EXECUTE'),'anon cannot read detail');
END $$;
ROLLBACK;
