-- Do not downgrade an already active shared registry as an additive slice.
-- The production G2 inventory has enabled consumers and complete readiness;
-- its registry transition needs its own coordinated, gated operation.
DO $active_registry_guard$
BEGIN
  IF EXISTS (SELECT 1 FROM public.occasions WHERE COALESCE((data->>'client_sync_v1')::boolean,false))
    AND EXISTS (SELECT 1 FROM public.client_sync_component_sources)
    AND NOT EXISTS (SELECT 1 FROM public.client_sync_component_sources
      WHERE registry_version=(SELECT max(registry_version) FROM public.client_sync_component_sources)
        AND NOT cutover_ready) THEN
    RAISE EXCEPTION 'active shared registry: defer canonical mutation metadata until coordinated readiness transition';
  END IF;
END $active_registry_guard$;
-- Current slice only; no global readiness or capability activation.
INSERT INTO public.client_sync_component_sources(registry_version,component,source_relation,scope_resolver,tracked_columns,canonical_writers,legacy_writers,disposition,test_factory) VALUES
(1,'private_profile','public.user_group_info','user_group_info.occasion/members',ARRAY['title','description','type','place','data']::text[],ARRAY['save_user_group_client_sync_v1','delete_user_group_client_sync_v1','replace_group_assignments_client_sync_v1','import_profiles_client_sync_v1','game_guess_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','create_reception_user_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[],ARRAY['import_user_group_assignments','import_occasion_users_from_csv','delete_occasion_user','delete_occasion_user_ws','game_guess','process_occasion_auto_import/service ticket import']::text[],'migrate','user_group_factory'),
(1,'private_profile','public.user_groups','group -> occasion/members',ARRAY['user','group','is_admin']::text[],ARRAY['save_user_group_client_sync_v1','delete_user_group_client_sync_v1','replace_group_assignments_client_sync_v1','import_profiles_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','create_reception_user_v1','game_guess_client_sync_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[],ARRAY['import_user_group_assignments','import_occasion_users_from_csv','delete_occasion_user','delete_occasion_user_ws','game_guess','process_occasion_auto_import/service ticket import']::text[],'migrate','user_group_membership_factory'),
(1,'private_activity','public.activities','activities.occasion',ARRAY['title','description','data','type','is_hidden','order']::text[],ARRAY['publish_activities_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[],ARRAY['update_activities','shift_occasion_schedule_backward','process_occasion_auto_import/service ticket import']::text[],'migrate','activity_factory'),
(1,'private_activity','public.activity_assignments','activity -> activities.occasion',ARRAY['activity_id','user','start_time','end_time','title','description','data']::text[],ARRAY['publish_activities_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[],ARRAY['update_activities','shift_occasion_schedule_backward','process_occasion_auto_import/service ticket import']::text[],'migrate','activity_assignment_factory'),
(1,'private_activity','public.activity_assignment_places','assignment -> activity -> occasion',ARRAY['assignment_id','place_id']::text[],ARRAY['publish_activities_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[],ARRAY['update_activities','shift_occasion_schedule_backward','process_occasion_auto_import/service ticket import']::text[],'migrate','activity_assignment_factory'),
(1,'private_activity','public.activity_assignment_events','assignment -> activity -> occasion',ARRAY['assignment_id','event_id']::text[],ARRAY['publish_activities_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[],ARRAY['update_activities','shift_occasion_schedule_backward','process_occasion_auto_import/service ticket import']::text[],'migrate','activity_assignment_factory'),
(1,'private_profile','public.places','places -> owning/referencing groups -> members/companion owners',ARRAY['title','description','coordinates','icon','is_hidden','type']::text[],ARRAY['save_user_group_client_sync_v1','delete_user_group_client_sync_v1','save_place_client_sync_v1','move_place_client_sync_v1','delete_place_client_sync_v1']::text[],ARRAY['save_place_location','shared map direct DML']::text[],'migrate','canonical_group_factory')
ON CONFLICT(registry_version,component,source_relation) DO UPDATE SET scope_resolver=EXCLUDED.scope_resolver,tracked_columns=EXCLUDED.tracked_columns,canonical_writers=EXCLUDED.canonical_writers,legacy_writers=EXCLUDED.legacy_writers,test_factory=EXCLUDED.test_factory,cutover_ready=false;
