-- Effective forward registry, not the historical expansion parser.
DO $$ BEGIN
PERFORM assert_true(EXISTS(SELECT 1 FROM public.client_sync_component_sources WHERE registry_version=1 AND component='private_profile' AND source_relation='public.user_group_info'::regclass AND canonical_writers=ARRAY['save_user_group_client_sync_v1','delete_user_group_client_sync_v1','replace_group_assignments_client_sync_v1','import_profiles_client_sync_v1','game_guess_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','create_reception_user_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[] AND legacy_writers=ARRAY['import_user_group_assignments','import_occasion_users_from_csv','delete_occasion_user','delete_occasion_user_ws','game_guess','process_occasion_auto_import/service ticket import']::text[] AND NOT cutover_ready),'effective registry private_profile/public.user_group_info');
PERFORM assert_true(EXISTS(SELECT 1 FROM public.client_sync_component_sources WHERE registry_version=1 AND component='private_profile' AND source_relation='public.user_groups'::regclass AND canonical_writers=ARRAY['save_user_group_client_sync_v1','delete_user_group_client_sync_v1','replace_group_assignments_client_sync_v1','import_profiles_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','create_reception_user_v1','game_guess_client_sync_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[] AND legacy_writers=ARRAY['import_user_group_assignments','import_occasion_users_from_csv','delete_occasion_user','delete_occasion_user_ws','game_guess','process_occasion_auto_import/service ticket import']::text[] AND NOT cutover_ready),'effective registry private_profile/public.user_groups');
PERFORM assert_true(EXISTS(SELECT 1 FROM public.client_sync_component_sources WHERE registry_version=1 AND component='private_activity' AND source_relation='public.activities'::regclass AND canonical_writers=ARRAY['publish_activities_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[] AND legacy_writers=ARRAY['update_activities','shift_occasion_schedule_backward','process_occasion_auto_import/service ticket import']::text[] AND NOT cutover_ready),'effective registry private_activity/public.activities');
PERFORM assert_true(EXISTS(SELECT 1 FROM public.client_sync_component_sources WHERE registry_version=1 AND component='private_activity' AND source_relation='public.activity_assignments'::regclass AND canonical_writers=ARRAY['publish_activities_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[] AND legacy_writers=ARRAY['update_activities','shift_occasion_schedule_backward','process_occasion_auto_import/service ticket import']::text[] AND NOT cutover_ready),'effective registry private_activity/public.activity_assignments');
PERFORM assert_true(EXISTS(SELECT 1 FROM public.client_sync_component_sources WHERE registry_version=1 AND component='private_activity' AND source_relation='public.activity_assignment_places'::regclass AND canonical_writers=ARRAY['publish_activities_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[] AND legacy_writers=ARRAY['update_activities','shift_occasion_schedule_backward','process_occasion_auto_import/service ticket import']::text[] AND NOT cutover_ready),'effective registry private_activity/public.activity_assignment_places');
PERFORM assert_true(EXISTS(SELECT 1 FROM public.client_sync_component_sources WHERE registry_version=1 AND component='private_activity' AND source_relation='public.activity_assignment_events'::regclass AND canonical_writers=ARRAY['publish_activities_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','record_account_deletion_sync_v1','delete_occasion_internal_v1','import_users_from_tickets_client_sync_v1','cancel_reception_registration_v1']::text[] AND legacy_writers=ARRAY['update_activities','shift_occasion_schedule_backward','process_occasion_auto_import/service ticket import']::text[] AND NOT cutover_ready),'effective registry private_activity/public.activity_assignment_events');
PERFORM assert_true(EXISTS(SELECT 1 FROM public.client_sync_component_sources WHERE registry_version=1 AND component='private_profile' AND source_relation='public.places'::regclass AND canonical_writers=ARRAY['save_user_group_client_sync_v1','delete_user_group_client_sync_v1','save_place_client_sync_v1','move_place_client_sync_v1','delete_place_client_sync_v1']::text[] AND legacy_writers=ARRAY['save_place_location','shared map direct DML']::text[] AND NOT cutover_ready),'effective registry private_profile/public.places');
PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.client_sync_component_sources WHERE source_relation='public.activity_history'::regclass),'history-only commands have no fake sync component');
END $$;
