-- Run with current Google SQL in one transaction; every fixture is rolled back.
DO $$
DECLARE org bigint:=970001; other_org bigint:=970002; usr uuid; other_usr uuid;
  a uuid:=gen_random_uuid(); owner uuid:=gen_random_uuid(); second_owner uuid:=gen_random_uuid(); r jsonb;
  state text:=repeat('s',43); nonce text:=repeat('n',43); challenge text:=repeat('c',43);
  bootstrap text:=repeat('b',43); handoff text:=repeat('h',43); cont text:=repeat('t',43); fresh text:=repeat('f',43);
  caught boolean; count_before bigint;
BEGIN
  PERFORM set_config('request.jwt.claim.role','service_role',true);
  INSERT INTO public.organizations(id,title,data) VALUES(org,'Google proof','{"IS_REGISTRATION_ENABLED":true}'),(other_org,'Other proof','{}');
  INSERT INTO public.external_login_clients(client_id,organization,platform,origin,redirect_uri,enabled)
  VALUES('google-sql-proof',org,'web','https://proof.invalid','https://proof.invalid/google-auth',true);
  PERFORM assert_eq(public.format_auth_email(1,' Jan@Example.com '),'1+jan@example.com','raw normalization');
  PERFORM assert_eq(public.format_auth_email(1,'1+jan@example.com'),'1+1+jan@example.com','raw numeric plus preserved');
  PERFORM assert_eq(public.format_auth_email(1,'jan+1@example.com'),'1+jan+1@example.com','alias preserved');
  PERFORM assert_true(NOT has_function_privilege('anon','public.google_auth_transition_v1(text,uuid,text,jsonb)','EXECUTE'),'no anon trusted identity writes');
  PERFORM assert_true(NOT has_function_privilege('authenticated','public.acquire_existing_user_session_lease_v1(uuid,uuid)','EXECUTE'),'no authenticated mint');
  usr:=public.create_user_in_organization_with_data_pure(org,'person@example.com','original-password','{}');
  other_usr:=public.create_user_in_organization_with_data_pure(other_org,'person@example.com','other-password','{}');
  PERFORM assert_true(usr<>other_usr,'same email different tenant UUID');
  PERFORM assert_true(public.acquire_existing_user_session_lease_v1(usr,owner) IS NOT NULL,'first lease');
  PERFORM assert_true(public.acquire_existing_user_session_lease_v1(usr,second_owner) IS NULL,'concurrent lease refused');
  PERFORM public.release_existing_user_session_lease_v1(usr,second_owner);
  PERFORM assert_true(public.check_existing_user_session_lease_v1(usr,owner) IS NOT NULL,'stale owner cannot release');
  PERFORM public.release_existing_user_session_lease_v1(usr,owner);
  r:=public.google_auth_transition_v1('start',a,bootstrap,jsonb_build_object('clientId','google-sql-proof','organization',org,'origin','https://proof.invalid','challenge',challenge,'stateHash',state,'nonceHash',nonce,'verifierEncrypted','encrypted-fixture'));
  r:=public.google_auth_transition_v1('bootstrap',a,bootstrap,jsonb_build_object('browserHash','cookie-proof'));
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('provider',a,state,jsonb_build_object('browserHash','wrong','issuer','https://accounts.google.com','subject','sub-proof')); EXCEPTION WHEN OTHERS THEN caught:=true; END;
  PERFORM assert_true(caught,'wrong browser rejected');
  r:=public.google_auth_transition_v1('provider',a,state,jsonb_build_object('browserHash','cookie-proof','issuer','https://accounts.google.com','subject','sub-proof','email','person@example.com','mailboxVerified',true,'handoffHash',handoff));
  r:=public.google_auth_transition_v1('claim',a,handoff,jsonb_build_object('challenge',challenge,'continuationHash',cont));
  PERFORM assert_eq(r->>'status','awaiting_account_proof','email match requires password proof');
  PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.external_login_identities WHERE user_id=usr),'no automatic linking');
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('claim',a,handoff,jsonb_build_object('challenge',challenge,'continuationHash',cont)); EXCEPTION WHEN OTHERS THEN caught:=true; END;
  PERFORM assert_true(caught,'handoff replay rejected');
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('link',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',fresh,'provenUser',other_usr)); EXCEPTION WHEN OTHERS THEN caught:=true; END;
  PERFORM assert_true(caught,'cross tenant proof rejected');
  r:=public.google_auth_transition_v1('link',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',fresh,'provenUser',usr));
  PERFORM assert_eq(r->>'target_user',usr::text,'proven original UUID linked');
  r:=public.google_auth_transition_v1('issue',a,fresh,jsonb_build_object('challenge',challenge));
  r:=public.google_auth_transition_v1('finish',a,fresh,jsonb_build_object('challenge',challenge));
  PERFORM assert_eq(r->>'status','consumed','one finish');
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('issue',a,fresh,jsonb_build_object('challenge',challenge)); EXCEPTION WHEN OTHERS THEN caught:=true; END;
  PERFORM assert_true(caught,'consumed attempt cannot remint');
  -- Disconnect requires provider binding plus fresh proof of the same UUID.
  a:=gen_random_uuid(); state:=repeat('x',43); handoff:=repeat('y',43);
  r:=public.google_auth_transition_v1('start',a,bootstrap,jsonb_build_object('intent','unlink','clientId','google-sql-proof','organization',org,'origin','https://proof.invalid','challenge',challenge,'stateHash',state,'nonceHash',nonce));
  r:=public.google_auth_transition_v1('bootstrap',a,bootstrap,jsonb_build_object('browserHash','cookie-proof'));
  r:=public.google_auth_transition_v1('provider',a,state,jsonb_build_object('browserHash','cookie-proof','issuer','https://accounts.google.com','subject','sub-proof','email','person@example.com','mailboxVerified',true,'handoffHash',handoff));
  r:=public.google_auth_transition_v1('claim',a,handoff,jsonb_build_object('challenge',challenge,'continuationHash',cont));
  PERFORM assert_eq(r->>'status','awaiting_account_proof','disconnect requires fresh proof');
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('unlink',a,cont,jsonb_build_object('challenge',challenge,'provenUser',other_usr)); EXCEPTION WHEN OTHERS THEN caught:=true; END;
  PERFORM assert_true(caught,'cannot disconnect another tenant UUID');
  r:=public.google_auth_transition_v1('unlink',a,cont,jsonb_build_object('challenge',challenge,'provenUser',usr));
  PERFORM assert_eq(r->>'status','consumed','disconnect consumed');
  PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.external_login_identities WHERE user_id=usr),'disconnect removes only bound identity');
  PERFORM assert_true(public.resolve_existing_user_session_v1(usr) IS NOT NULL,'disconnect preserves original account');
  -- MFA continuation stores only encrypted session server-side; proof binds UUID.
  a:=gen_random_uuid(); state:=repeat('M',43); handoff:=repeat('N',43);
  r:=public.google_auth_transition_v1('start',a,bootstrap,jsonb_build_object('clientId','google-sql-proof','organization',org,'origin','https://proof.invalid','challenge',challenge,'stateHash',state,'nonceHash',nonce));
  r:=public.google_auth_transition_v1('bootstrap',a,bootstrap,jsonb_build_object('browserHash','cookie-proof'));
  r:=public.google_auth_transition_v1('provider',a,state,jsonb_build_object('browserHash','cookie-proof','issuer','https://accounts.google.com','subject','mfa-sub','email','person@example.com','mailboxVerified',true,'handoffHash',handoff));
  r:=public.google_auth_transition_v1('claim',a,handoff,jsonb_build_object('challenge',challenge,'continuationHash',cont));
  r:=public.google_auth_transition_v1('mfa_begin',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',fresh,'provenUser',usr,'sessionEncrypted','cipher-only'));
  PERFORM assert_eq(r->>'status','awaiting_mfa','MFA has no ready identity');
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('issue',a,fresh,jsonb_build_object('challenge',challenge)); EXCEPTION WHEN OTHERS THEN caught:=true; END;
  PERFORM assert_true(caught,'MFA cannot be skipped');
  r:=public.google_auth_transition_v1('mfa_proven',a,fresh,jsonb_build_object('challenge',challenge,'provenUser',usr));
  PERFORM assert_true(r->>'mfa_session_encrypted' IS NULL,'MFA proof clears encrypted session');
  -- New account initialization is one transaction with strict registration policy.
  a:=gen_random_uuid(); state:=repeat('u',43); handoff:=repeat('v',43);
  r:=public.google_auth_transition_v1('start',a,bootstrap,jsonb_build_object('clientId','google-sql-proof','organization',org,'origin','https://proof.invalid','challenge',challenge,'stateHash',state,'nonceHash',nonce));
  r:=public.google_auth_transition_v1('bootstrap',a,bootstrap,jsonb_build_object('browserHash','cookie-proof'));
  r:=public.google_auth_transition_v1('provider',a,state,jsonb_build_object('browserHash','cookie-proof','issuer','https://accounts.google.com','subject','new-sub','email','new@example.com','mailboxVerified',true,'handoffHash',handoff));
  r:=public.google_auth_transition_v1('claim',a,handoff,jsonb_build_object('challenge',challenge,'continuationHash',cont));
  PERFORM assert_eq(r->>'status','awaiting_profile','new profile');
  UPDATE public.organizations SET data='{}' WHERE id=org;
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('register',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',fresh,'profile',jsonb_build_object('name','New','surname','Person'),'consent',true,'password','random-unshared-password')); EXCEPTION WHEN OTHERS THEN caught:=SQLERRM='registration_disabled'; END;
  PERFORM assert_true(caught,'missing registration flag fail closed');
  UPDATE public.organizations SET data='{"IS_REGISTRATION_ENABLED":true}' WHERE id=org;
  r:=public.google_auth_transition_v1('register',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',fresh,'profile',jsonb_build_object('name','New','surname','Person','email','attacker@example.com'),'consent',true,'password','random-unshared-password'));
  usr:=(r->>'target_user')::uuid;
  PERFORM assert_true(EXISTS(SELECT 1 FROM public.user_info WHERE id=usr AND email_readonly='new@example.com'),'profile cannot override verified email');
  PERFORM assert_true((SELECT count(*)=1 FROM public.unit_users WHERE "user"=usr AND is_manager),'exactly one own unit');
  PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.occasion_users WHERE "user"=usr),'no event membership created');
  DELETE FROM public.unit_users WHERE "user"=usr;
  DELETE FROM public.user_info WHERE id=usr;
  PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.external_login_identities WHERE user_id=usr),'public deletion removes identity before auth deletion');
  PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.external_login_attempts WHERE id=a),'public deletion removes targeted attempts');
  PERFORM assert_true(public.resolve_existing_user_session_v1(usr) IS NULL,'orphan auth user cannot mint');
  -- External Google mailboxes cannot register until a fresh mailbox proof.
  a:=gen_random_uuid(); state:=repeat('W',43); handoff:=repeat('Z',43);
  r:=public.google_auth_transition_v1('start',a,bootstrap,jsonb_build_object('clientId','google-sql-proof','organization',org,'origin','https://proof.invalid','challenge',challenge,'stateHash',state,'nonceHash',nonce));
  r:=public.google_auth_transition_v1('bootstrap',a,bootstrap,jsonb_build_object('browserHash','cookie-proof'));
  r:=public.google_auth_transition_v1('provider',a,state,jsonb_build_object('browserHash','cookie-proof','issuer','https://accounts.google.com','subject','mailbox-sub','email','mailbox@example.com','mailboxVerified',false,'handoffHash',handoff));
  r:=public.google_auth_transition_v1('claim',a,handoff,jsonb_build_object('challenge',challenge,'continuationHash',cont));
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('register',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',fresh,'profile',jsonb_build_object('name','Mailbox','surname','Person'),'consent',true,'password','private-random-password')); EXCEPTION WHEN OTHERS THEN caught:=SQLERRM='mailbox_proof_required'; END;
  PERFORM assert_true(caught,'external mailbox proof required before user creation');
  r:=public.google_auth_transition_v1('mailbox_send',a,cont,jsonb_build_object('challenge',challenge,'mailboxHash','correct-attempt-bound-hmac'));
  FOR i IN 1..5 LOOP
    r:=public.google_auth_transition_v1('mailbox_verify',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',cont,'mailboxHash','wrong-hmac'));
    PERFORM assert_eq((r->>'mailbox_tries')::integer,i,'mailbox tries persist');
    PERFORM assert_true(NOT (r->>'mailbox_verified')::boolean,'wrong code never proves mailbox');
  END LOOP;
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('mailbox_verify',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',fresh,'mailboxHash','correct-attempt-bound-hmac')); EXCEPTION WHEN OTHERS THEN caught:=true; END;
  PERFORM assert_true(caught,'sixth mailbox attempt rejected even with correct code');
  UPDATE public.external_login_attempts SET expires_at=clock_timestamp()-interval '1 second' WHERE id=a;
  caught:=false;
  BEGIN PERFORM public.google_auth_transition_v1('mailbox_send',a,cont,jsonb_build_object('challenge',challenge)); EXCEPTION WHEN OTHERS THEN caught:=SQLERRM='attempt_expired'; END;
  PERFORM assert_true(caught,'expired continuation rejected');
  PERFORM public.cleanup_external_login_v1();
  PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.external_login_attempts WHERE id=a),'TTL cleanup removes private proof');
  -- A password registration racing Google registration falls back to proof.
  a:=gen_random_uuid(); state:=repeat('C',43); handoff:=repeat('D',43);
  r:=public.google_auth_transition_v1('start',a,bootstrap,jsonb_build_object('clientId','google-sql-proof','organization',org,'origin','https://proof.invalid','challenge',challenge,'stateHash',state,'nonceHash',nonce));
  r:=public.google_auth_transition_v1('bootstrap',a,bootstrap,jsonb_build_object('browserHash','cookie-proof'));
  r:=public.google_auth_transition_v1('provider',a,state,jsonb_build_object('browserHash','cookie-proof','issuer','https://accounts.google.com','subject','race-sub','email','race@example.com','mailboxVerified',true,'handoffHash',handoff));
  r:=public.google_auth_transition_v1('claim',a,handoff,jsonb_build_object('challenge',challenge,'continuationHash',cont));
  usr:=public.create_user_in_organization_with_data_pure(org,'race@example.com','existing-password','{}');
  SELECT count(*) INTO count_before FROM auth.users;
  r:=public.google_auth_transition_v1('register',a,cont,jsonb_build_object('challenge',challenge,'continuationHash',fresh,'profile',jsonb_build_object('name','Race','surname','Person'),'consent',true,'password','private-random-password'));
  PERFORM assert_eq(r->>'status','awaiting_account_proof','racing registration requires original password');
  PERFORM assert_true((SELECT count(*)=count_before FROM auth.users),'registration race creates no duplicate Auth account');
  PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.external_login_identities WHERE user_id=usr),'race does not link by email');
  UPDATE auth.users SET banned_until=clock_timestamp()+interval '1 hour' WHERE id=usr;
  PERFORM assert_true(public.resolve_existing_user_session_v1(usr) IS NULL,'banned users cannot mint');
  UPDATE auth.users SET banned_until=NULL WHERE id=usr;
  PERFORM public.invalidate_external_login_for_user_v1(usr);
  PERFORM assert_true(NOT EXISTS(SELECT 1 FROM public.external_login_attempts WHERE id=a),'domain deletion invalidates unlinked email attempts too');
  -- The local SQL harness is postgres, which is an explicit operator bypass.
  -- ACLs above prove anon/authenticated cannot invoke these RPCs.
END $$;
