-- Read-only G2 inventory. Execute only through canonical activation/access with separate authority.
SELECT jsonb_build_object(
 'database',current_database(),
 'migrations',(SELECT jsonb_agg(jsonb_build_object('version',version,'name',name) ORDER BY version) FROM supabase_migrations.schema_migrations),
 'functions',(SELECT jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'sha256',encode(extensions.digest(convert_to(pg_get_functiondef(p.oid),'UTF8'),'sha256'),'hex'),'acl',p.proacl,'authenticatedExecute',has_function_privilege('authenticated',p.oid,'EXECUTE'),'anonExecute',has_function_privilege('anon',p.oid,'EXECUTE')) ORDER BY p.oid::regprocedure::text) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=ANY(ARRAY['record_account_deletion_sync_v1','advance_group_profile_heads_internal_v1','import_profiles_client_sync_v1','delete_occasion_user_client_sync_v1','delete_owned_companion_internal_v1','game_guess_client_sync_v1','delete_user_group_client_sync_v1','lock_group_occasion_internal_v1','group_profile_impacts_internal_v1','assert_group_place_owner_internal_v1','get_user_group_command_data_v1','get_user_group_editor_bundle_v1','get_user_group_info_with_users','move_place_client_sync_v1','get_private_profile_payload_v1','mutate_map_entity_internal_v1','remove_occasion_user_domain_internal_v1','replace_group_assignments_client_sync_v1','save_user_group_client_sync_v1','activity_time_internal_v1','normalize_activity_graph_internal_v1','activity_history_graph_internal_v1','activity_graph_history_internal_v1','current_activity_graph_internal_v1','replace_activities_graph_internal_v1','update_activities','write_activity_history_internal_v1','clear_activity_draft_internal_v1','save_activity_history','delete_autosave_history','lock_activity_aggregate_internal_v1','lock_activity_editor_internal_v1','retain_activity_history_internal_v1','save_activity_draft_client_sync_v1','discard_activity_draft_client_sync_v1','publish_activities_client_sync_v1','remove_user_activity_internal_v1','get_activity_editor_session_v1','get_latest_autosave','get_activity_history_version','list_activity_history','get_activities_for_edit','import_occasion_users_from_csv_apply_v1','import_occasion_users_from_csv_internal_v1','import_occasion_users_from_csv','import_user_group_assignments_internal_v1','import_user_group_assignments','delete_occasion_user','delete_occasion_user_ws','import_users_from_tickets','import_users_from_tickets_client_sync_v1','complete_profile_inventory_membership_mutation_v1','save_place_location','create_reception_user_v1','cancel_reception_registration_v1','profile_group_import_state_internal_v1','game_guess'])),
 'effectiveDml',(SELECT jsonb_agg(jsonb_build_object('relation',relation::text,'role',role_name,'tableInsert',has_table_privilege(role_name,relation,'INSERT'),'tableUpdate',has_table_privilege(role_name,relation,'UPDATE'),'tableDelete',has_table_privilege(role_name,relation,'DELETE'),'tableTruncate',has_table_privilege(role_name,relation,'TRUNCATE'),'columnInsert',has_any_column_privilege(role_name,relation,'INSERT'),'columnUpdate',has_any_column_privilege(role_name,relation,'UPDATE'))) FROM unnest(ARRAY['public.user_group_info','public.user_groups','public.activities','public.activity_assignments','public.activity_assignment_places','public.activity_assignment_events','public.activity_history','public.places']::regclass[]) relation CROSS JOIN unnest(ARRAY['anon','authenticated']) role_name),
 'acl',(SELECT jsonb_agg(jsonb_build_object('relation',c.oid::regclass::text,'acl',c.relacl,'columns',COALESCE((SELECT jsonb_agg(jsonb_build_object('column',attname,'acl',attacl)) FROM pg_attribute WHERE attrelid=c.oid AND attnum>0 AND NOT attisdropped AND attacl IS NOT NULL),'[]'))) FROM pg_class c WHERE c.oid=ANY(ARRAY['public.user_group_info','public.user_groups','public.activities','public.activity_assignments','public.activity_assignment_places','public.activity_assignment_events','public.activity_history','public.places']::regclass[])),
 'roleMemberships',(SELECT jsonb_agg(to_jsonb(m)) FROM pg_auth_members m),
 'enabledOccasions',(SELECT jsonb_agg(jsonb_build_object('id',id,'organization',organization,'link',link)) FROM public.occasions WHERE COALESCE((data->>'client_sync_v1')::boolean,false)),
 'registry',(SELECT jsonb_agg(to_jsonb(s)) FROM public.client_sync_component_sources s),
 'internalFacadeCallers',(SELECT jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'sha256',encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex'))) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prosrc ~ '(delete_occasion_user|import_user_group_assignments|update_activities|save_activity_history|delete_autosave_history|save_place_location)\s*\(')
) AS result;
