
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const projectRoot = path.resolve(__dirname, '../');
const projectVersionScript = path.resolve(__dirname, 'release/project_version.mjs');

// 1. Get Version from Args or Env, otherwise read the canonical project config.
let version = process.argv[2] || process.env.VERSION;

if (!version) {
    try {
        version = execFileSync(process.execPath, [projectVersionScript, '--full'], {
            cwd: projectRoot,
            encoding: 'utf8',
        }).trim();
    } catch (error) {
        console.error('Error: Could not read VERSION from automation/project.conf', error.message);
        process.exit(1);
    }
}

console.log(`Configuring Version: ${version}`);

const webClientRoot = path.resolve(projectRoot, 'web_client');

// Paths
const pubspecPath = path.resolve(projectRoot, 'pubspec.yaml');
const packageJsonPath = path.resolve(webClientRoot, 'package.json');
const packageLockPath = path.resolve(webClientRoot, 'package-lock.json');
const versionJsPath = path.resolve(webClientRoot, 'src/version.js');

// 2. Update pubspec.yaml
if (fs.existsSync(pubspecPath)) {
    let content = fs.readFileSync(pubspecPath, 'utf8');
    // Regex to replace version: x.x.x+x
    const regex = /^version:\s*(.+)$/m;
    if (regex.test(content)) {
        const currentParams = content.match(regex)[1];
        if (currentParams.trim() !== version) {
            content = content.replace(regex, `version: ${version}`);
            fs.writeFileSync(pubspecPath, content);
            console.log(`Updated pubspec.yaml to ${version}`);
        } else {
             console.log(`pubspec.yaml already at ${version}`);
        }
    } else {
        console.warn('Warning: Could not find "version:" in pubspec.yaml');
    }
} else {
    console.warn(`Warning: pubspec.yaml not found at ${pubspecPath}`);
}

// 3. Update package.json
// Package.json versions should be semver (no +build).
const semVer = version.split('+')[0];

if (fs.existsSync(packageJsonPath)) {
    try {
        const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        if (pkg.version !== semVer) {
            pkg.version = semVer;
            fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n');
            console.log(`Updated package.json to ${semVer}`);
        } else {
            console.log(`package.json already at ${semVer}`);
        }
    } catch (e) {
        console.error('Error parsing package.json:', e);
    }
} else {
    console.warn(`Warning: package.json not found at ${packageJsonPath}`);
}

// npm records the root package version twice in package-lock.json. Keep both
// copies synchronized with package.json so one release cannot advertise
// multiple versions depending on which manifest a tool reads.
if (fs.existsSync(packageLockPath)) {
    try {
        const lock = JSON.parse(fs.readFileSync(packageLockPath, 'utf8'));
        let changed = false;
        if (lock.version !== semVer) {
            lock.version = semVer;
            changed = true;
        }
        if (lock.packages?.[''] && lock.packages[''].version !== semVer) {
            lock.packages[''].version = semVer;
            changed = true;
        }
        if (changed) {
            fs.writeFileSync(packageLockPath, JSON.stringify(lock, null, 2) + '\n');
            console.log(`Updated package-lock.json to ${semVer}`);
        } else {
            console.log(`package-lock.json already at ${semVer}`);
        }
    } catch (e) {
        console.error('Error parsing package-lock.json:', e);
        process.exitCode = 1;
    }
}

// 4. Update src/version.js
const versionJsContent = `// Auto-generated by automation/configure_version.js
export const APP_VERSION = '${version}';
`;

let currentVersionJs = '';
if (fs.existsSync(versionJsPath)) {
    currentVersionJs = fs.readFileSync(versionJsPath, 'utf8');
}

if (currentVersionJs !== versionJsContent) {
    fs.writeFileSync(versionJsPath, versionJsContent);
    console.log(`Updated src/version.js to ${version}`);
} else {
    console.log(`src/version.js is up to date.`);
}

// 5. Stamp both HTML entry points so startup can identify its generation
// before any external JavaScript is available.
for (const entryPoint of ['web/index.html', 'web_client/index.html']) {
    const indexPath = path.resolve(projectRoot, entryPoint);
    if (!fs.existsSync(indexPath)) continue;
    const indexHtml = fs.readFileSync(indexPath, 'utf8');
    const buildVersionRegex = /(window\.__FESTAPP_BUILD_VERSION__\s*=\s*)"[^"]*"/;
    if (!buildVersionRegex.test(indexHtml)) {
        console.warn(`Warning: Could not find window.__FESTAPP_BUILD_VERSION__ in ${entryPoint}`);
        continue;
    }
    const updatedIndex = indexHtml.replace(buildVersionRegex, `$1"${version}"`);
    if (updatedIndex !== indexHtml) {
        fs.writeFileSync(indexPath, updatedIndex);
        console.log(`Updated ${entryPoint} __FESTAPP_BUILD_VERSION__ to ${version}`);
    }
}
